[ 2.6.1.2 ] Latest CI infrastructure
The changes in this commit have been created by copying in the
respective files from the master branch as of today (2020-10-12).
Originally, these changes have been spread over dozens of commits
which I did not have the patience to cherry-pick.

Exception: I picked the changes in Agda.cabal by hand using emacs
ediff-buffers.